// Golden-string parity tests for the ported question builders (questions.ts)
// against the REAL Python builders in launchkit/backend/app/rr.py.
//
// Build + run from the repo root:
//   (cd apps/launchkit && npx tsc src/domain/*.ts --outDir ../../tools/tests/domain/.build \
//      --module commonjs --target ES2022 --strict --skipLibCheck) \
//   && node --test "tools/tests/domain/*.test.mjs"
//
// GOLDEN strings below were generated 2026-08-31 by running the actual Python
// stage runners with rr.ask monkeypatched to capture the constructed question
// (rescore additionally stubs rr._fetch_url_text). Representative command:
//
//   /Users/shashidharbabu/rocketride-apps-gtm/launchkit/.venv/bin/python -c "
//   import sys, asyncio, json
//   sys.path.insert(0, '/Users/shashidharbabu/rocketride-apps-gtm/launchkit/backend')
//   from app import rr
//   cap = []
//   async def fake(pipe, q):
//       cap.append(q); return {'relevant': True, 'confidence': 0.9, 'why': 'w', 'reply': 'r'}
//   rr.ask = fake
//   profile = json.load(open('/Users/shashidharbabu/rocketride-apps-gtm/launchkit/backend/evals/fixtures/profiles/termdiff.json'))
//   asyncio.run(rr.run_understand('', 'https://termdiff.dev', 'make it terser'))
//   print(json.dumps(cap.pop()))"
//
// Same technique for every golden: run_understand / build_signals_question /
// run_asset / run_commercial / run_targets / run_brand / rescore_signals with
// the termdiff fixture profile and the literal inputs reconstructed below.
// This proves pyJsonDumps parity with CPython json.dumps (default separators,
// ensure_ascii=True, insertion order) byte for byte.

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { test } from 'node:test';

const require = createRequire(import.meta.url);
const q = require('./.build/questions.js');

const FIXTURE = new URL(
  '../../../launchkit/backend/evals/fixtures/profiles/termdiff.json', import.meta.url);
const profile = JSON.parse(readFileSync(FIXTURE, 'utf8'));

const GOLDENS = {
  understand_norepo_feedback:
    "Produce the app profile for this app.\nRepository URL: NONE SUPPLIED — analyse from the live site alone and set analysis_degraded true.\nLive product URL: https://termdiff.dev\nBUILDER_FEEDBACK (the app's builder reviewed a previous draft and asks you to incorporate this): make it terser",
  understand_repo:
    "Produce the app profile for this app.\nRepository URL: https://github.com/acme/termdiff\nLive product URL: https://termdiff.dev",
  signals_default:
    "APP_PROFILE: {\"one_liner\": \"Rust-powered terminal git diff viewer with side-by-side, word-level highlighting that renders huge diffs instantly.\", \"description\": \"termdiff is an open-source CLI that replaces git's default pager with a side-by-side, syntax-highlighted diff view. It does word-level change highlighting, hunk navigation with single keystrokes, and stays fast on monorepo-scale diffs. It ships as a single static binary and drops into existing git aliases with zero config.\", \"category\": \"Developer Tools / CLI\", \"target_user\": \"Terminal-first software engineers who review diffs many times a day\", \"icp\": {\"who\": \"Senior engineers and OSS maintainers who live in the terminal and review large diffs daily\", \"pain\": \"Default git diff output is unreadable for large changes, and existing pagers choke or misalign on monorepo-scale diffs\", \"current_alternatives\": [\"delta\", \"diff-so-fancy\", \"difftastic\", \"Plain git diff piped through less\"], \"buying_trigger\": \"Joining a monorepo team or picking up heavy code-review duties where diff readability becomes a daily tax\"}, \"differentiators\": [\"Renders a 10,000-line diff in 38ms \\u2014 an order of magnitude faster than existing fancy-diff pagers\", \"True side-by-side view in the terminal with word-level highlighting, not just intra-line color\", \"Single static binary with zero config: respects existing git aliases and core.pager settings\"], \"proof_points\": [\"4,200 GitHub stars within the first year\", \"Benchmark in README: renders a 10k-line diff in 38ms on an M1 MacBook Air\", \"Listed on Terminal Trove and packaged in Homebrew core\"], \"tech_stack\": [\"Rust\", \"tree-sitter\", \"crossterm\"], \"pricing_current\": \"free (MIT-licensed open source)\", \"voice\": {\"tone\": [\"terse\", \"precise\", \"engineer-to-engineer\"], \"sample_phrase\": \"Your diffs, side by side, in 38 milliseconds.\"}, \"maturity\": {\"stage\": \"launched\", \"signals\": [\"Tagged 1.x releases with a changelog\", \"Homebrew core formula accepted\", \"Issues triaged within days; 30+ external contributors\"]}, \"gaps\": [\"No demo GIF on the website\", \"No comparison page against delta and difftastic\", \"No Windows Terminal testing documented\"], \"confidence\": {\"overall\": 0.9, \"notes\": \"Strong evidence from repo, benchmarks, and package listings. Adoption numbers beyond stars are self-reported.\"}}\nICP_PAIN: Default git diff output is unreadable for large changes, and existing pagers choke or misalign on monorepo-scale diffs\nCOMMUNITIES: [\"opensource\", \"SideProject\", \"selfhosted\", \"webdev\", \"devtools\", \"programming\"]",
  signals_communities:
    "APP_PROFILE: {\"one_liner\": \"Rust-powered terminal git diff viewer with side-by-side, word-level highlighting that renders huge diffs instantly.\", \"description\": \"termdiff is an open-source CLI that replaces git's default pager with a side-by-side, syntax-highlighted diff view. It does word-level change highlighting, hunk navigation with single keystrokes, and stays fast on monorepo-scale diffs. It ships as a single static binary and drops into existing git aliases with zero config.\", \"category\": \"Developer Tools / CLI\", \"target_user\": \"Terminal-first software engineers who review diffs many times a day\", \"icp\": {\"who\": \"Senior engineers and OSS maintainers who live in the terminal and review large diffs daily\", \"pain\": \"Default git diff output is unreadable for large changes, and existing pagers choke or misalign on monorepo-scale diffs\", \"current_alternatives\": [\"delta\", \"diff-so-fancy\", \"difftastic\", \"Plain git diff piped through less\"], \"buying_trigger\": \"Joining a monorepo team or picking up heavy code-review duties where diff readability becomes a daily tax\"}, \"differentiators\": [\"Renders a 10,000-line diff in 38ms \\u2014 an order of magnitude faster than existing fancy-diff pagers\", \"True side-by-side view in the terminal with word-level highlighting, not just intra-line color\", \"Single static binary with zero config: respects existing git aliases and core.pager settings\"], \"proof_points\": [\"4,200 GitHub stars within the first year\", \"Benchmark in README: renders a 10k-line diff in 38ms on an M1 MacBook Air\", \"Listed on Terminal Trove and packaged in Homebrew core\"], \"tech_stack\": [\"Rust\", \"tree-sitter\", \"crossterm\"], \"pricing_current\": \"free (MIT-licensed open source)\", \"voice\": {\"tone\": [\"terse\", \"precise\", \"engineer-to-engineer\"], \"sample_phrase\": \"Your diffs, side by side, in 38 milliseconds.\"}, \"maturity\": {\"stage\": \"launched\", \"signals\": [\"Tagged 1.x releases with a changelog\", \"Homebrew core formula accepted\", \"Issues triaged within days; 30+ external contributors\"]}, \"gaps\": [\"No demo GIF on the website\", \"No comparison page against delta and difftastic\", \"No Windows Terminal testing documented\"], \"confidence\": {\"overall\": 0.9, \"notes\": \"Strong evidence from repo, benchmarks, and package listings. Adoption numbers beyond stars are self-reported.\"}}\nICP_PAIN: Default git diff output is unreadable for large changes, and existing pagers choke or misalign on monorepo-scale diffs\nCOMMUNITIES: [\"rust\", \"commandline\"]",
  asset_full:
    "ASSET_TYPE: x_post\nAPP_PROFILE: {\"one_liner\": \"Rust-powered terminal git diff viewer with side-by-side, word-level highlighting that renders huge diffs instantly.\", \"description\": \"termdiff is an open-source CLI that replaces git's default pager with a side-by-side, syntax-highlighted diff view. It does word-level change highlighting, hunk navigation with single keystrokes, and stays fast on monorepo-scale diffs. It ships as a single static binary and drops into existing git aliases with zero config.\", \"category\": \"Developer Tools / CLI\", \"target_user\": \"Terminal-first software engineers who review diffs many times a day\", \"icp\": {\"who\": \"Senior engineers and OSS maintainers who live in the terminal and review large diffs daily\", \"pain\": \"Default git diff output is unreadable for large changes, and existing pagers choke or misalign on monorepo-scale diffs\", \"current_alternatives\": [\"delta\", \"diff-so-fancy\", \"difftastic\", \"Plain git diff piped through less\"], \"buying_trigger\": \"Joining a monorepo team or picking up heavy code-review duties where diff readability becomes a daily tax\"}, \"differentiators\": [\"Renders a 10,000-line diff in 38ms \\u2014 an order of magnitude faster than existing fancy-diff pagers\", \"True side-by-side view in the terminal with word-level highlighting, not just intra-line color\", \"Single static binary with zero config: respects existing git aliases and core.pager settings\"], \"proof_points\": [\"4,200 GitHub stars within the first year\", \"Benchmark in README: renders a 10k-line diff in 38ms on an M1 MacBook Air\", \"Listed on Terminal Trove and packaged in Homebrew core\"], \"tech_stack\": [\"Rust\", \"tree-sitter\", \"crossterm\"], \"pricing_current\": \"free (MIT-licensed open source)\", \"voice\": {\"tone\": [\"terse\", \"precise\", \"engineer-to-engineer\"], \"sample_phrase\": \"Your diffs, side by side, in 38 milliseconds.\"}, \"maturity\": {\"stage\": \"launched\", \"signals\": [\"Tagged 1.x releases with a changelog\", \"Homebrew core formula accepted\", \"Issues triaged within days; 30+ external contributors\"]}, \"gaps\": [\"No demo GIF on the website\", \"No comparison page against delta and difftastic\", \"No Windows Terminal testing documented\"], \"confidence\": {\"overall\": 0.9, \"notes\": \"Strong evidence from repo, benchmarks, and package listings. Adoption numbers beyond stars are self-reported.\"}}\nBRAND_DNA: {\"palette\": [\"#000\", \"#fff\"], \"voice\": \"terse \\u2014 engineer-to-engineer\"}\nTARGET: {\"name\": \"r/rust\", \"kind\": \"subreddit\", \"url\": \"https://reddit.com/r/rust\", \"rank\": 1}\nTONE: confident\nBUILDER_FEEDBACK (the builder reviewed a previous draft of this asset and asks for these changes): shorter — punchier",
  asset_min:
    "ASSET_TYPE: show_hn\nAPP_PROFILE: {\"one_liner\": \"Rust-powered terminal git diff viewer with side-by-side, word-level highlighting that renders huge diffs instantly.\", \"description\": \"termdiff is an open-source CLI that replaces git's default pager with a side-by-side, syntax-highlighted diff view. It does word-level change highlighting, hunk navigation with single keystrokes, and stays fast on monorepo-scale diffs. It ships as a single static binary and drops into existing git aliases with zero config.\", \"category\": \"Developer Tools / CLI\", \"target_user\": \"Terminal-first software engineers who review diffs many times a day\", \"icp\": {\"who\": \"Senior engineers and OSS maintainers who live in the terminal and review large diffs daily\", \"pain\": \"Default git diff output is unreadable for large changes, and existing pagers choke or misalign on monorepo-scale diffs\", \"current_alternatives\": [\"delta\", \"diff-so-fancy\", \"difftastic\", \"Plain git diff piped through less\"], \"buying_trigger\": \"Joining a monorepo team or picking up heavy code-review duties where diff readability becomes a daily tax\"}, \"differentiators\": [\"Renders a 10,000-line diff in 38ms \\u2014 an order of magnitude faster than existing fancy-diff pagers\", \"True side-by-side view in the terminal with word-level highlighting, not just intra-line color\", \"Single static binary with zero config: respects existing git aliases and core.pager settings\"], \"proof_points\": [\"4,200 GitHub stars within the first year\", \"Benchmark in README: renders a 10k-line diff in 38ms on an M1 MacBook Air\", \"Listed on Terminal Trove and packaged in Homebrew core\"], \"tech_stack\": [\"Rust\", \"tree-sitter\", \"crossterm\"], \"pricing_current\": \"free (MIT-licensed open source)\", \"voice\": {\"tone\": [\"terse\", \"precise\", \"engineer-to-engineer\"], \"sample_phrase\": \"Your diffs, side by side, in 38 milliseconds.\"}, \"maturity\": {\"stage\": \"launched\", \"signals\": [\"Tagged 1.x releases with a changelog\", \"Homebrew core formula accepted\", \"Issues triaged within days; 30+ external contributors\"]}, \"gaps\": [\"No demo GIF on the website\", \"No comparison page against delta and difftastic\", \"No Windows Terminal testing documented\"], \"confidence\": {\"overall\": 0.9, \"notes\": \"Strong evidence from repo, benchmarks, and package listings. Adoption numbers beyond stars are self-reported.\"}}",
  commercial_pricing:
    "TASK: pricing\nAPP_PROFILE: {\"one_liner\": \"Rust-powered terminal git diff viewer with side-by-side, word-level highlighting that renders huge diffs instantly.\", \"description\": \"termdiff is an open-source CLI that replaces git's default pager with a side-by-side, syntax-highlighted diff view. It does word-level change highlighting, hunk navigation with single keystrokes, and stays fast on monorepo-scale diffs. It ships as a single static binary and drops into existing git aliases with zero config.\", \"category\": \"Developer Tools / CLI\", \"target_user\": \"Terminal-first software engineers who review diffs many times a day\", \"icp\": {\"who\": \"Senior engineers and OSS maintainers who live in the terminal and review large diffs daily\", \"pain\": \"Default git diff output is unreadable for large changes, and existing pagers choke or misalign on monorepo-scale diffs\", \"current_alternatives\": [\"delta\", \"diff-so-fancy\", \"difftastic\", \"Plain git diff piped through less\"], \"buying_trigger\": \"Joining a monorepo team or picking up heavy code-review duties where diff readability becomes a daily tax\"}, \"differentiators\": [\"Renders a 10,000-line diff in 38ms \\u2014 an order of magnitude faster than existing fancy-diff pagers\", \"True side-by-side view in the terminal with word-level highlighting, not just intra-line color\", \"Single static binary with zero config: respects existing git aliases and core.pager settings\"], \"proof_points\": [\"4,200 GitHub stars within the first year\", \"Benchmark in README: renders a 10k-line diff in 38ms on an M1 MacBook Air\", \"Listed on Terminal Trove and packaged in Homebrew core\"], \"tech_stack\": [\"Rust\", \"tree-sitter\", \"crossterm\"], \"pricing_current\": \"free (MIT-licensed open source)\", \"voice\": {\"tone\": [\"terse\", \"precise\", \"engineer-to-engineer\"], \"sample_phrase\": \"Your diffs, side by side, in 38 milliseconds.\"}, \"maturity\": {\"stage\": \"launched\", \"signals\": [\"Tagged 1.x releases with a changelog\", \"Homebrew core formula accepted\", \"Issues triaged within days; 30+ external contributors\"]}, \"gaps\": [\"No demo GIF on the website\", \"No comparison page against delta and difftastic\", \"No Windows Terminal testing documented\"], \"confidence\": {\"overall\": 0.9, \"notes\": \"Strong evidence from repo, benchmarks, and package listings. Adoption numbers beyond stars are self-reported.\"}}",
  targets_curated:
    "APP_PROFILE: {\"one_liner\": \"Rust-powered terminal git diff viewer with side-by-side, word-level highlighting that renders huge diffs instantly.\", \"description\": \"termdiff is an open-source CLI that replaces git's default pager with a side-by-side, syntax-highlighted diff view. It does word-level change highlighting, hunk navigation with single keystrokes, and stays fast on monorepo-scale diffs. It ships as a single static binary and drops into existing git aliases with zero config.\", \"category\": \"Developer Tools / CLI\", \"target_user\": \"Terminal-first software engineers who review diffs many times a day\", \"icp\": {\"who\": \"Senior engineers and OSS maintainers who live in the terminal and review large diffs daily\", \"pain\": \"Default git diff output is unreadable for large changes, and existing pagers choke or misalign on monorepo-scale diffs\", \"current_alternatives\": [\"delta\", \"diff-so-fancy\", \"difftastic\", \"Plain git diff piped through less\"], \"buying_trigger\": \"Joining a monorepo team or picking up heavy code-review duties where diff readability becomes a daily tax\"}, \"differentiators\": [\"Renders a 10,000-line diff in 38ms \\u2014 an order of magnitude faster than existing fancy-diff pagers\", \"True side-by-side view in the terminal with word-level highlighting, not just intra-line color\", \"Single static binary with zero config: respects existing git aliases and core.pager settings\"], \"proof_points\": [\"4,200 GitHub stars within the first year\", \"Benchmark in README: renders a 10k-line diff in 38ms on an M1 MacBook Air\", \"Listed on Terminal Trove and packaged in Homebrew core\"], \"tech_stack\": [\"Rust\", \"tree-sitter\", \"crossterm\"], \"pricing_current\": \"free (MIT-licensed open source)\", \"voice\": {\"tone\": [\"terse\", \"precise\", \"engineer-to-engineer\"], \"sample_phrase\": \"Your diffs, side by side, in 38 milliseconds.\"}, \"maturity\": {\"stage\": \"launched\", \"signals\": [\"Tagged 1.x releases with a changelog\", \"Homebrew core formula accepted\", \"Issues triaged within days; 30+ external contributors\"]}, \"gaps\": [\"No demo GIF on the website\", \"No comparison page against delta and difftastic\", \"No Windows Terminal testing documented\"], \"confidence\": {\"overall\": 0.9, \"notes\": \"Strong evidence from repo, benchmarks, and package listings. Adoption numbers beyond stars are self-reported.\"}}\nCURATED_VENUES: [{\"name\": \"Hacker News\", \"kind\": \"forum\", \"url\": \"https://news.ycombinator.com\", \"submission_url\": \"https://news.ycombinator.com/submit\", \"tags\": \"dev\"}]",
  brand_campaigns:
    "TASK: campaigns\nAPP_PROFILE: {\"one_liner\": \"Rust-powered terminal git diff viewer with side-by-side, word-level highlighting that renders huge diffs instantly.\", \"description\": \"termdiff is an open-source CLI that replaces git's default pager with a side-by-side, syntax-highlighted diff view. It does word-level change highlighting, hunk navigation with single keystrokes, and stays fast on monorepo-scale diffs. It ships as a single static binary and drops into existing git aliases with zero config.\", \"category\": \"Developer Tools / CLI\", \"target_user\": \"Terminal-first software engineers who review diffs many times a day\", \"icp\": {\"who\": \"Senior engineers and OSS maintainers who live in the terminal and review large diffs daily\", \"pain\": \"Default git diff output is unreadable for large changes, and existing pagers choke or misalign on monorepo-scale diffs\", \"current_alternatives\": [\"delta\", \"diff-so-fancy\", \"difftastic\", \"Plain git diff piped through less\"], \"buying_trigger\": \"Joining a monorepo team or picking up heavy code-review duties where diff readability becomes a daily tax\"}, \"differentiators\": [\"Renders a 10,000-line diff in 38ms \\u2014 an order of magnitude faster than existing fancy-diff pagers\", \"True side-by-side view in the terminal with word-level highlighting, not just intra-line color\", \"Single static binary with zero config: respects existing git aliases and core.pager settings\"], \"proof_points\": [\"4,200 GitHub stars within the first year\", \"Benchmark in README: renders a 10k-line diff in 38ms on an M1 MacBook Air\", \"Listed on Terminal Trove and packaged in Homebrew core\"], \"tech_stack\": [\"Rust\", \"tree-sitter\", \"crossterm\"], \"pricing_current\": \"free (MIT-licensed open source)\", \"voice\": {\"tone\": [\"terse\", \"precise\", \"engineer-to-engineer\"], \"sample_phrase\": \"Your diffs, side by side, in 38 milliseconds.\"}, \"maturity\": {\"stage\": \"launched\", \"signals\": [\"Tagged 1.x releases with a changelog\", \"Homebrew core formula accepted\", \"Issues triaged within days; 30+ external contributors\"]}, \"gaps\": [\"No demo GIF on the website\", \"No comparison page against delta and difftastic\", \"No Windows Terminal testing documented\"], \"confidence\": {\"overall\": 0.9, \"notes\": \"Strong evidence from repo, benchmarks, and package listings. Adoption numbers beyond stars are self-reported.\"}}\nBRAND_DNA: {\"palette\": [\"#000\", \"#fff\"], \"voice\": \"terse \\u2014 engineer-to-engineer\"}\nBUILDER_FEEDBACK (the builder reviewed a previous draft and asks for these changes): bolder",
  rescore:
    "You are a strict relevance judge AND reply writer for launch outreach. Below is an APP and the ACTUAL CONTENT of a discussion thread. First decide if replying to this thread with this app is genuinely helpful to the thread's author — i.e. they are asking for, or struggling with, what this app does. Passing mentions of the topic do NOT count. IF AND ONLY IF relevant, also write the reply the builder should post. REPLY RULES: open by engaging the author's SPECIFIC situation — reference a concrete detail from the thread (their tool, error, constraint, or exact question); NEVER open with a canned phrase like 'I built a tool for exactly this'. Genuinely help FIRST in 2-4 sentences — the reply must be worth upvoting even if they never click. Then, only if the app truly fits, one plain-words sentence disclosing you built it, mentioning it ONCE with {APP_URL}. Match the norms of platform 'hackernews' — Reddit and HN are hostile to marketing. Max 120 words. No emoji, no hype words, no bullet lists. Reply with ONLY RFC 8259 JSON: {\"relevant\": true|false, \"confidence\": number 0-1, \"why\": string (one sentence), \"reply\": string (\"\" when not relevant)}\n\nAPP: {\"one_liner\": \"Rust-powered terminal git diff viewer with side-by-side, word-level highlighting that renders huge diffs instantly.\", \"description\": \"termdiff is an open-source CLI that replaces git's default pager with a side-by-side, syntax-highlighted diff view. It does word-level change highlighting, hunk navigation with single keystrokes, and stays fast on monorepo-scale diffs. It ships as a single static binary and drops into existing git aliases with zero config.\", \"icp\": {\"who\": \"Senior engineers and OSS maintainers who live in the terminal and review large diffs daily\", \"pain\": \"Default git diff output is unreadable for large changes, and existing pagers choke or misalign on monorepo-scale diffs\", \"current_alternatives\": [\"delta\", \"diff-so-fancy\", \"difftastic\", \"Plain git diff piped through less\"], \"buying_trigger\": \"Joining a monorepo team or picking up heavy code-review duties where diff readability becomes a daily tax\"}, \"differentiators\": [\"Renders a 10,000-line diff in 38ms \\u2014 an order of magnitude faster than existing fancy-diff pagers\", \"True side-by-side view in the terminal with word-level highlighting, not just intra-line color\", \"Single static binary with zero config: respects existing git aliases and core.pager settings\"], \"proof_points\": [\"4,200 GitHub stars within the first year\", \"Benchmark in README: renders a 10k-line diff in 38ms on an M1 MacBook Air\", \"Listed on Terminal Trove and packaged in Homebrew core\"], \"voice\": {\"tone\": [\"terse\", \"precise\", \"engineer-to-engineer\"], \"sample_phrase\": \"Your diffs, side by side, in 38 milliseconds.\"}}\n\nTHREAD CONTENT: Thread text — user asks: how do I get side-by-side diffs in the terminal? delta chokes on huge files.",
  rescore_default_platform:
    "You are a strict relevance judge AND reply writer for launch outreach. Below is an APP and the ACTUAL CONTENT of a discussion thread. First decide if replying to this thread with this app is genuinely helpful to the thread's author — i.e. they are asking for, or struggling with, what this app does. Passing mentions of the topic do NOT count. IF AND ONLY IF relevant, also write the reply the builder should post. REPLY RULES: open by engaging the author's SPECIFIC situation — reference a concrete detail from the thread (their tool, error, constraint, or exact question); NEVER open with a canned phrase like 'I built a tool for exactly this'. Genuinely help FIRST in 2-4 sentences — the reply must be worth upvoting even if they never click. Then, only if the app truly fits, one plain-words sentence disclosing you built it, mentioning it ONCE with {APP_URL}. Match the norms of platform 'forum' — Reddit and HN are hostile to marketing. Max 120 words. No emoji, no hype words, no bullet lists. Reply with ONLY RFC 8259 JSON: {\"relevant\": true|false, \"confidence\": number 0-1, \"why\": string (one sentence), \"reply\": string (\"\" when not relevant)}\n\nAPP: {\"one_liner\": \"Rust-powered terminal git diff viewer with side-by-side, word-level highlighting that renders huge diffs instantly.\", \"description\": \"termdiff is an open-source CLI that replaces git's default pager with a side-by-side, syntax-highlighted diff view. It does word-level change highlighting, hunk navigation with single keystrokes, and stays fast on monorepo-scale diffs. It ships as a single static binary and drops into existing git aliases with zero config.\", \"icp\": {\"who\": \"Senior engineers and OSS maintainers who live in the terminal and review large diffs daily\", \"pain\": \"Default git diff output is unreadable for large changes, and existing pagers choke or misalign on monorepo-scale diffs\", \"current_alternatives\": [\"delta\", \"diff-so-fancy\", \"difftastic\", \"Plain git diff piped through less\"], \"buying_trigger\": \"Joining a monorepo team or picking up heavy code-review duties where diff readability becomes a daily tax\"}, \"differentiators\": [\"Renders a 10,000-line diff in 38ms \\u2014 an order of magnitude faster than existing fancy-diff pagers\", \"True side-by-side view in the terminal with word-level highlighting, not just intra-line color\", \"Single static binary with zero config: respects existing git aliases and core.pager settings\"], \"proof_points\": [\"4,200 GitHub stars within the first year\", \"Benchmark in README: renders a 10k-line diff in 38ms on an M1 MacBook Air\", \"Listed on Terminal Trove and packaged in Homebrew core\"], \"voice\": {\"tone\": [\"terse\", \"precise\", \"engineer-to-engineer\"], \"sample_phrase\": \"Your diffs, side by side, in 38 milliseconds.\"}}\n\nTHREAD CONTENT: Thread text — user asks: how do I get side-by-side diffs in the terminal? delta chokes on huge files.",
  rescore_thread_text:
    "Thread text — user asks: how do I get side-by-side diffs in the terminal? delta chokes on huge files.",
};

test('understand: no repo (NONE SUPPLIED branch) + builder feedback', () => {
  assert.equal(q.buildUnderstandQuestion('', 'https://termdiff.dev', 'make it terser'),
               GOLDENS.understand_norepo_feedback);
});

test('understand: repo + site, no feedback', () => {
  assert.equal(q.buildUnderstandQuestion('https://github.com/acme/termdiff', 'https://termdiff.dev'),
               GOLDENS.understand_repo);
});

test('signals: fallback communities + ICP_PAIN extraction', () => {
  assert.equal(q.buildSignalsQuestion(profile), GOLDENS.signals_default);
});

test('signals: explicit communities', () => {
  assert.equal(q.buildSignalsQuestion(profile, ['rust', 'commandline']),
               GOLDENS.signals_communities);
});

test('signals: empty communities list falls back (Python truthiness)', () => {
  assert.equal(q.buildSignalsQuestion(profile, []), GOLDENS.signals_default);
});

test('asset: full payload — brand dna, target, tone, feedback, section order', () => {
  const target = { name: 'r/rust', kind: 'subreddit', url: 'https://reddit.com/r/rust', rank: 1 };
  const dna = { palette: ['#000', '#fff'], voice: 'terse — engineer-to-engineer' };
  assert.equal(
    q.buildAssetQuestion('x_post', profile, target, 'confident', 'shorter — punchier', dna),
    GOLDENS.asset_full);
});

test('asset: minimal payload (profile only)', () => {
  assert.equal(q.buildAssetQuestion('show_hn', profile), GOLDENS.asset_min);
});

test('commercial: pricing task', () => {
  assert.equal(q.buildCommercialQuestion('pricing', profile), GOLDENS.commercial_pricing);
});

test('targets: curated venue pool rides along', () => {
  const curated = [{ name: 'Hacker News', kind: 'forum', url: 'https://news.ycombinator.com',
                     submission_url: 'https://news.ycombinator.com/submit', tags: 'dev' }];
  assert.equal(q.buildTargetsQuestion(profile, curated), GOLDENS.targets_curated);
});

test('brand: campaigns with dna + feedback', () => {
  const dna = { palette: ['#000', '#fff'], voice: 'terse — engineer-to-engineer' };
  assert.equal(q.buildBrandQuestion('campaigns', profile, '', dna, 'bolder'),
               GOLDENS.brand_campaigns);
});

test('rescore: judge prompt verbatim, explicit platform', () => {
  const summary = q.buildRescoreSummary(profile);
  assert.equal(q.buildRescoreQuestion(summary, 'hackernews', GOLDENS.rescore_thread_text),
               GOLDENS.rescore);
});

test('rescore: missing platform key defaults to forum', () => {
  const summary = q.buildRescoreSummary(profile);
  assert.equal(q.buildRescoreQuestion(summary, undefined, GOLDENS.rescore_thread_text),
               GOLDENS.rescore_default_platform);
});

test('rescore summary: key order is the tuple order, only present keys', () => {
  const summary = q.buildRescoreSummary(profile);
  assert.deepEqual(Object.keys(summary),
    ['one_liner', 'description', 'icp', 'differentiators', 'proof_points', 'voice']);
  const partial = q.buildRescoreSummary({ voice: 'v', one_liner: 'x' });
  assert.deepEqual(Object.keys(partial), ['one_liner', 'voice']);
});
