/**
 * Machine checks the draft gate runs after the model answers, one list per
 * platform, distilled with the rulebooks (apps/launchkit/rulebooks/<platform>.md).
 * kind: max_chars | min_words | max_words | max_count | forbidden_regex |
 * required_prefix; field names a draft field, or "all" for every string field.
 */
export type RuleCheck = { id: string; description: string; kind: string; value: string; field: string; flags?: string };

export const RULEBOOK_CHECKS: Record<string, RuleCheck[]> = {
  'x_post': [
    { id: 'x_post_max_chars', description: 'Post over 280 characters, {APP_URL} included', kind: 'max_chars', value: '280', field: 'post' },
    { id: 'x_post_min_words', description: 'Post under 8 words', kind: 'min_words', value: '8', field: 'post' },
    { id: 'x_post_url_at_most_once', description: '{APP_URL} more than once', kind: 'forbidden_regex', value: '\\{APP_URL\\}[\\s\\S]*\\{APP_URL\\}', field: 'post' },
    { id: 'x_no_raw_links', description: 'A raw link; the only link is the {APP_URL} placeholder', kind: 'forbidden_regex', value: 'https?://|www\\.', field: '*' },
    { id: 'x_thread_max_count', description: 'More than 4 thread tweets', kind: 'max_count', value: '4', field: 'thread_extension' },
    { id: 'x_thread_tweet_max_chars', description: 'A thread tweet over 250 characters', kind: 'max_chars', value: '250', field: 'thread_extension' },
    { id: 'x_thread_no_numbering', description: 'A 1/ 2. 3) prefix on a thread tweet', kind: 'forbidden_regex', value: '^\\s*\\d+\\s*[/.)]', field: 'thread_extension' },
    { id: 'x_post_no_thread_marker', description: 'A thread marker on the post', kind: 'forbidden_regex', value: '🧵|^\\s*thread\\b|\\s1/\\s*$|\\(1/\\d*\\)', field: 'post' },
    { id: 'x_alt_max_count', description: 'More than two alt variants', kind: 'max_count', value: '2', field: 'alt_variants' },
    { id: 'x_alt_max_chars', description: 'An alt variant over 280 characters', kind: 'max_chars', value: '280', field: 'alt_variants' },
    { id: 'x_no_dash', description: 'Em or en dash', kind: 'forbidden_regex', value: '[\u2014\u2013]', field: '*' },
    { id: 'x_no_s_word', description: 'The banned launch verb', kind: 'forbidden_regex', value: '\\bs[h]ip(s|ped|ping)?\\b', field: '*' },
    { id: 'x_no_hype', description: 'Hype words, announcement filler or an Nx multiplier', kind: 'forbidden_regex', value: 'game.?chang|revolutionar|groundbreak|\\bviral\\b|seamless|unleash|supercharg|\\b\\d+x\\b|\\d+ times (faster|better|more)|excited to announce|thrilled to|big news', field: '*' },
    { id: 'x_post_no_announcement_opener', description: 'An announcement or rhetorical-question opener', kind: 'forbidden_regex', value: '^\\s*(introducing|excited|thrilled|big news|ever wonder|what if|have you ever|are you)', field: 'post' },
    { id: 'x_no_engagement_asks', description: 'A follow, repost, like or scarcity ask', kind: 'forbidden_regex', value: 'follow (me|us|for)|repost (if|this)|retweet|\\bRT\\b|like (if|this)|tag (a |someone)|link in bio|limited (spots|time|seats)|only \\d+ (spots|seats|left)|last chance|don\'?t miss|upvote', field: '*' },
    { id: 'x_no_competitor_framing', description: 'Better-than-X positioning', kind: 'forbidden_regex', value: 'better than|worse than|\\bunlike [A-Z]|\\bis dead\\b|stop using|\\bkills? [A-Z]|\\bbeats [A-Z]', field: '*' },
    { id: 'x_no_ai_tells', description: 'AI-tell phrasing', kind: 'forbidden_regex', value: 'keep (thinking about|coming back to)|pattern I keep seeing|let that sink in|here\'?s the thing|hot take|\\b[1-4] ?a\\.?m\\b|worth watching', field: '*' },
    { id: 'x_hashtag_limit', description: 'More than one hashtag', kind: 'forbidden_regex', value: '#\\w+[\\s\\S]*#\\w+', field: '*' },
    { id: 'x_no_exclamation_or_ellipsis', description: 'An exclamation mark or a trailing ellipsis', kind: 'forbidden_regex', value: '!|\\.\\.\\.|…', field: '*' },
  ],
  'linkedin_post': [
    { id: 'post_min_words', description: 'Post under 120 words', kind: 'min_words', value: '120', field: 'post' },
    { id: 'post_max_words', description: 'Post over 200 words', kind: 'max_words', value: '200', field: 'post' },
    { id: 'post_max_chars', description: 'Post over 1,400 characters', kind: 'max_chars', value: '1400', field: 'post' },
    { id: 'hook_line_max_chars', description: 'Line 1 over 140 characters (mobile truncation)', kind: 'forbidden_regex', value: '^[^\\n]{141,}', field: 'post' },
    { id: 'hook_line_no_reflex_question', description: 'Rhetorical-question opener in line 1', kind: 'forbidden_regex', value: '^[^\\n]{0,30}\\b(?:ever wondered?|have you ever|did you know|what if i told you|are you (?:tired|sick) of|are you still)\\b', field: 'post' },
    { id: 'no_url_in_body', description: 'A link in the body; the link goes in the first comment', kind: 'forbidden_regex', value: 'https?://|\\bwww\\.|\\{APP_URL\\}', field: 'post' },
    { id: 'first_comment_line_present', description: 'Missing the "Link in the first comment." line', kind: 'forbidden_regex', value: '^(?![\\s\\S]*\\blink (?:is )?in the (?:first )?comments?\\b)', field: 'post' },
    { id: 'hashtags_max_three', description: 'Four or more hashtags', kind: 'forbidden_regex', value: '#\\w+(?:[\\s\\S]*?#\\w+){3}', field: 'post' },
    { id: 'hashtags_last_line_only', description: 'A hashtag before the last line', kind: 'forbidden_regex', value: '#\\w+[^\\n]*\\n[\\s\\S]*\\S', field: 'post' },
    { id: 'no_dashes', description: 'Em or en dash', kind: 'forbidden_regex', value: '[\u2014\u2013]', field: 'post' },
    { id: 'invisible_chars', description: 'Invisible characters (zero-width, joiner, soft hyphen)', kind: 'forbidden_regex', value: '[​-‏⁠﻿­     ᠎؜]', field: 'post' },
    { id: 'brand_banned_terms', description: 'The banned launch verb or the deprecated one-key framing', kind: 'forbidden_regex', value: '\\bs[h]ip(?:s|ped|ping)?\\b|universal\\s+api\\s+key', field: 'post' },
    { id: 'hype_terms', description: 'Hype words or multipliers', kind: 'forbidden_regex', value: 'game.?chang(?:er|ing)|groundbreaking|revolutionar(?:y|i[sz]e)|\\bviral\\b|seamless(?:ly)?|unleash|supercharge|\\b10x\\b|\\b\\d+x\\s+(?:faster|better|quicker|more)\\b|next[- ]gen\\b|world[- ]class|best[- ]in[- ]class|state[- ]of[- ]the[- ]art', field: 'post' },
    { id: 'competitor_framing', description: 'Better-than-X positioning', kind: 'forbidden_regex', value: '\\bbetter than\\b|\\bunlike (?:other|most|every|any|the rest)\\b|\\boutperforms?\\b|\\bcompetitors?\\b|\\balternative to\\b', field: 'post' },
    { id: 'engagement_bait', description: 'Engagement bait', kind: 'forbidden_regex', value: '\\bthoughts\\?|\\bagree\\?|\\bwho else\\b|\\bam i wrong\\?|\\bwho[\'’]s with me\\b|\\bcomment (?:yes|below|[\'"]\\w+[\'"])\\b|\\bdrop a comment\\b|\\bshare this with\\b|\\bfollow me\\b|\\btag (?:someone|a friend)\\b|\\brepost (?:if|this)\\b|\\blike (?:if|this post)\\b|\\blet that sink in\\b|\\bread that again\\b|\\bsave this for later\\b', field: 'post' },
    { id: 'slop_lexicon', description: 'AI-tell vocabulary', kind: 'forbidden_regex', value: '\\bdelve|\\bdeep[- ]dive|\\bdive deep\\b|\\bleverag(?:e|es|ed|ing)\\b|\\butili[sz](?:e|es|ed|ing)\\b|\\bembark on\\b|\\bfoster(?:s|ed|ing)?\\b|\\bfacilitat(?:e|es|ed|ing)\\b|\\bshowcas(?:e|es|ed|ing)\\b|\\bunlock(?:s|ed|ing)?\\b|\\belevat(?:e|es|ed|ing)\\b|\\bstreamlin(?:e|es|ed|ing)\\b|\\bspearhead|\\bcultivat(?:e|es|ed|ing)\\b|\\bamplif(?:y|ies|ied|ying)\\b|\\bcurat(?:e|es|ed|ing)\\b|\\bempower(?:s|ed|ing)?\\b|\\btransformative\\b|\\brobust(?:ly)?\\b|\\bpivotal\\b|\\bcrucial(?:ly)?\\b|\\bvital(?:ly)?\\b|\\bcomprehensive(?:ly)?\\b|\\bcutting[- ]edge\\b|\\bunparalleled\\b|\\binvaluable\\b|\\bmeticulous(?:ly)?\\b|\\bmyriad\\b|\\bmultifaceted\\b|\\bholistic(?:ally)?\\b|\\bbespoke\\b|\\binnovative\\b|\\bprofound(?:ly)?\\b|\\bremarkabl[ey]\\b|\\bcompelling\\b|\\btapestry\\b|\\brealm\\b|\\blandscape\\b|\\bjourney\\b|\\btestament to\\b|\\bcornerstone\\b|\\bbeacon\\b|\\bparadigm\\b|\\bsynergy\\b|\\btreasure trove\\b|\\bplethora\\b|\\barsenal\\b|\\bnorth star\\b|\\bmoreover\\b|\\bfurthermore\\b|\\badditionally\\b|\\bnevertheless\\b|\\bconsequently\\b|\\bthus\\b|\\bhence\\b|\\bnotably\\b|\\bimportantly\\b|\\bultimately\\b|\\bin essence\\b|\\bin conclusion\\b|\\bwhen it comes to\\b|\\bin order to\\b|\\ba wide range of\\b|\\bit is worth noting\\b|\\bin today[\'’]s (?:fast[- ]paced|digital)\\b|\\bever[- ](?:evolving|changing)\\b|\\blet[\'’]s face it\\b|\\bhere[\'’]s the thing\\b|\\bpicture this\\b|\\bimagine a world\\b|\\bit[\'’]s no secret\\b|\\bwe[\'’]ve all been there\\b|\\bthe choice is yours\\b|\\bfood for thought\\b|\\bthe future is here\\b|\\bat the end of the day\\b|\\bmove the needle\\b|\\bneedle[- ]moving\\b|\\bhad the opportunity to\\b|\\b(?:i[\'’]m |i am )?(?:excited|thrilled|humbled|proud|delighted) to (?:announce|share)\\b|\\bwithout further ado\\b|\\bbuckle up\\b|\\bthe harsh truth\\b|\\bspoiler alert\\b|\\byou[\'’]re welcome\\b', field: 'post' },
    { id: 'structural_tells', description: 'The "it is not X, it is Y" shape', kind: 'forbidden_regex', value: 'it[\'’]s not (?:just|only) [^.!?\\n]{2,60}[,.] it[\'’]s\\b|\\bnot only\\b[^.!?\\n]{2,80}\\bbut also\\b|\\b(?:this|it) is(?:n[\'’]t| not) about [^.!?\\n]{2,60}[.!] it[\'’]s about\\b|(?:^|\\n)[ \\t]*(?:the result|the best part|the kicker|the catch)\\?[ \\t]*(?:\\n|$)|\\bhere[\'’]s what (?:i|we) learned\\b|(?:^|\\n)[ \\t]*(?:in summary|to summari[sz]e|in conclusion)\\b', field: 'post' },
    { id: 'banned_emoji', description: 'A reflex emoji (rocket, fire, bulb, sparkles, dart)', kind: 'forbidden_regex', value: '[🚀🔥💡✨🎯]', field: 'post' },
    { id: 'staccato_lines', description: 'Six or more one-sentence lines in a row', kind: 'forbidden_regex', value: '(?:^|\\n)(?:[^\\n]{1,60}[.!?][ \\t]*\\n){5}[^\\n]{1,60}[.!?]', field: 'post' },
    { id: 'bullet_dump', description: 'Four or more bullet lines', kind: 'forbidden_regex', value: '(?:(?:^|\\n)[ \\t]*[-*•][ \\t]+[^\\n]*){4}', field: 'post' },
    { id: 'post_all_caps_run', description: 'Three consecutive words in capitals', kind: 'forbidden_regex', value: '\\b[A-Z]{4,}(?:\\s+[A-Z]{4,}){2}\\b', field: 'post', flags: '' },
    { id: 'alt_hook_max_chars', description: 'Alternate hook over 140 characters', kind: 'max_chars', value: '140', field: 'alt_hook' },
    { id: 'alt_hook_single_line', description: 'Alternate hook is more than one line', kind: 'forbidden_regex', value: '\\n', field: 'alt_hook' },
    { id: 'alt_hook_no_dashes', description: 'Em or en dash in the alternate hook', kind: 'forbidden_regex', value: '[\u2014\u2013]', field: 'alt_hook' },
    { id: 'alt_hook_no_url', description: 'A link or placeholder in the alternate hook', kind: 'forbidden_regex', value: 'https?://|\\bwww\\.|\\{APP_URL\\}', field: 'alt_hook' },
    { id: 'alt_hook_brand_banned_terms', description: 'The banned launch verb in the alternate hook', kind: 'forbidden_regex', value: '\\bs[h]ip(?:s|ped|ping)?\\b|universal\\s+api\\s+key', field: 'alt_hook' },
    { id: 'alt_hook_hype_terms', description: 'Hype words in the alternate hook', kind: 'forbidden_regex', value: 'game.?chang(?:er|ing)|groundbreaking|revolutionar(?:y|i[sz]e)|\\bviral\\b|seamless(?:ly)?|unleash|supercharge|\\b10x\\b|\\b\\d+x\\s+(?:faster|better|quicker|more)\\b|next[- ]gen\\b|world[- ]class|best[- ]in[- ]class|state[- ]of[- ]the[- ]art', field: 'alt_hook' },
  ],
  'reddit_post': [
    { id: 'title_max_chars', description: 'Title over 100 characters', kind: 'max_chars', value: '100', field: 'title' },
    { id: 'title_min_words', description: 'Title under 6 words', kind: 'min_words', value: '6', field: 'title' },
    { id: 'title_max_words', description: 'Title over 16 words', kind: 'max_words', value: '16', field: 'title' },
    { id: 'title_no_show_hn', description: 'A Show HN title on Reddit', kind: 'forbidden_regex', value: '^\\s*Show HN:', field: 'title' },
    { id: 'title_no_bang_or_question', description: 'An exclamation or question mark in the title', kind: 'forbidden_regex', value: '[!?]', field: 'title' },
    { id: 'title_no_clickbait', description: 'Clickbait title', kind: 'forbidden_regex', value: '\\b(you won\'?t believe|this one (trick|thing)|changed my life|insane|crazy|mind-?blowing|must[- ]see)\\b', field: 'title' },
    { id: 'body_min_words', description: 'Body under 150 words', kind: 'min_words', value: '150', field: 'body' },
    { id: 'body_max_words', description: 'Body over 300 words', kind: 'max_words', value: '300', field: 'body' },
    { id: 'body_no_list_lines', description: 'A bullet or numbered list; flowing paragraphs only', kind: 'forbidden_regex', value: '^\\s*(?:[-*•]|\\d+[.)])\\s+', field: 'body' },
    { id: 'body_no_headings_or_bold', description: 'A markdown heading or bold', kind: 'forbidden_regex', value: '^\\s*#{1,6}\\s|\\*\\*[^*]+\\*\\*', field: 'body' },
    { id: 'body_no_tldr', description: 'A TL;DR line', kind: 'forbidden_regex', value: '\\btl;?dr\\b', field: 'body' },
    { id: 'body_app_url_max_once', description: '{APP_URL} more than once', kind: 'max_count', value: '1', field: 'body' },
    { id: 'body_no_raw_urls', description: 'A raw link; links only through {APP_URL}', kind: 'forbidden_regex', value: 'https?://|www\\.', field: 'body' },
    { id: 'body_no_lazy_closer', description: 'A lazy closing question', kind: 'forbidden_regex', value: '\\b(thoughts\\?|what do you think|let me know|would love to hear|any feedback is appreciated)\\b', field: 'body' },
    { id: 'no_vote_or_reciprocity_asks', description: 'A vote, star, follow or share ask', kind: 'forbidden_regex', value: '\\b(upvote|up-vote|star (the|my|our|this) repo|give (it|us) a star|follow (me|us)|share this|discount|promo code|exclusive offer|coupon|feedback for feedback|return the favou?r)\\b', field: 'body' },
    { id: 'no_dm_solicit', description: 'A DM solicitation', kind: 'forbidden_regex', value: '\\b(dm me|send me a dm|pm me|message me)\\b', field: 'body' },
    { id: 'no_hashtags', description: 'A hashtag', kind: 'forbidden_regex', value: '(^|\\s)#[A-Za-z]\\w*', field: 'all' },
    { id: 'no_emoji', description: 'An emoji', kind: 'forbidden_regex', value: '[\\u{1F000}-\\u{1FAFF}\\u{2600}-\\u{27BF}]', field: 'all' },
    { id: 'no_dashes', description: 'Em or en dash', kind: 'forbidden_regex', value: '[\u2014\u2013]', field: 'all' },
    { id: 'no_banned_verb', description: 'The banned launch verb', kind: 'forbidden_regex', value: '\\bsh[i]p(s|ped|ping)?\\b', field: 'all' },
    { id: 'no_hype', description: 'Hype words', kind: 'forbidden_regex', value: '\\b(game[- ]?chang\\w*|ground-?breaking|revolution(ary|i[sz]e\\w*)|vir(al|ality)|seam-?less(ly)?|unlea[s]h\\w*|super-?charge\\w*|\\d+x (faster|better|cheaper|more)|1[0]x)\\b', field: 'all' },
    { id: 'no_ai_tells', description: 'AI-tell vocabulary', kind: 'forbidden_regex', value: '\\b(leverag\\w*|utiliz\\w*|innovative|honest take|here\'?s the thing|the irony is|it\'?s funny how|nobody tells you|full transparency|excited to announce|thrilled to|in today\'?s)\\b', field: 'all' },
    { id: 'no_setup_pivot', description: 'The "not X, just Y" shape', kind: 'forbidden_regex', value: '(^|[.!?]\\s+)not [^,.]{1,40}, just\\b', field: 'body' },
    { id: 'no_better_than', description: 'Better-than-X positioning', kind: 'forbidden_regex', value: '\\b(better|faster|cheaper|smarter|simpler) than\\b', field: 'body' },
    { id: 'traction_numbers_need_proof', description: 'A traction number (users, MRR, a dollar figure) that must appear in the profile proof points', kind: 'forbidden_regex', value: '\\b\\d[\\d,.]*\\s?[km]?\\s*(users|customers|signups|sign-ups|downloads|stars|installs|teams|companies)\\b|\\bMRR\\b|\\bARR\\b|\\$\\s?\\d', field: 'body' },
    { id: 'warnings_present', description: 'The warnings list is empty', kind: 'min_words', value: '4', field: 'warnings' },
  ],
  'producthunt': [
    { id: 'ph_tagline_max_chars', description: 'Tagline over 60 characters', kind: 'max_chars', value: '60', field: 'tagline' },
    { id: 'ph_description_max_chars', description: 'Description over 260 characters', kind: 'max_chars', value: '260', field: 'description' },
    { id: 'ph_first_comment_min_words', description: 'Maker comment under 150 words', kind: 'min_words', value: '150', field: 'first_comment' },
    { id: 'ph_first_comment_max_words', description: 'Maker comment over 250 words', kind: 'max_words', value: '250', field: 'first_comment' },
    { id: 'ph_topics_max_count', description: 'More than 4 topics', kind: 'max_count', value: '4', field: 'topics' },
    { id: 'ph_name_max_chars', description: 'Name over 40 characters', kind: 'max_chars', value: '40', field: 'name' },
    { id: 'ph_no_vote_ask', description: 'A vote ask, in any form', kind: 'forbidden_regex', value: '\\b(up-?vot(e|es|ed|ing)|vot(e|es|ed|ing)|leaderboard|help us (win|reach)|reach (#|number )?1\\b|every vote|support (our|the) launch|love your support|your support (means|would))', field: 'all' },
    { id: 'ph_no_scarcity_or_reciprocity', description: 'Scarcity, a countdown or a vote swap', kind: 'forbidden_regex', value: '\\b(first \\d+ (users|people|makers|signups|hunters|customers)|limited (time|spots|offer)|only \\d+ (left|spots|seats)|ends (tonight|today|at midnight)|hurry|last chance|don\'?t miss|in return|return the favou?r|i\'?ll (upvote|support) yours)', field: 'all' },
    { id: 'ph_no_hype', description: 'Hype words', kind: 'forbidden_regex', value: '\\b(game.?chan[g]\\w*|revolutiona[r]\\w*|groundbreakin[g]|vira[l]|seamless\\w*|unleash\\w*|supercharg\\w*|world\'?s first|next-?gen\\w*|all-in-one|ai-powered|cutting-edge|best-in-class|the best|10x)\\b', field: 'all' },
    { id: 'ph_no_nx_multiplier', description: 'An Nx multiplier claim', kind: 'forbidden_regex', value: '\\b\\d+(\\.\\d+)?x\\b', field: 'all' },
    { id: 'ph_no_banned_verb_or_key_framing', description: 'The banned launch verb or the deprecated one-key framing', kind: 'forbidden_regex', value: '\\b(s[h]ip(s|ped|ping|pable)?|universal api ke[y])\\b', field: 'all' },
    { id: 'ph_no_dashes', description: 'Em or en dash', kind: 'forbidden_regex', value: '[\u2014\u2013]', field: 'all' },
    { id: 'ph_no_rocket', description: 'The rocket emoji', kind: 'forbidden_regex', value: '\\u{1F680}', field: 'all' },
    { id: 'ph_description_opener', description: 'Description opens with We/Our or a question', kind: 'forbidden_regex', value: '^\\s*(We|We\'re|We\'ve|Our)\\b|^[^.!?\\n]{0,120}\\?', field: 'description' },
    { id: 'ph_first_comment_exclamations', description: 'Three or more exclamation marks in the maker comment', kind: 'forbidden_regex', value: '![^!]*![^!]*!', field: 'first_comment' },
    { id: 'ph_no_social_proof_phrases', description: 'Social-proof phrasing or a star rating without a source', kind: 'forbidden_regex', value: '\\b(trusted by|loved by|used by (teams|companies|developers) at|join \\d[\\d,]*\\+? (users|developers|makers|teams)|\\d(\\.\\d)?/5|testimonials?)\\b|[★⭐]', field: 'all' },
    { id: 'ph_no_hashtags', description: 'A hashtag', kind: 'forbidden_regex', value: '(^|\\s)#[A-Za-z]', field: 'all' },
  ],
  'show_hn': [
    { id: 'title_required_prefix', description: 'Title does not start with "Show HN: "', kind: 'required_prefix', value: 'Show HN: ', field: 'title' },
    { id: 'title_max_chars', description: 'Title over 80 characters, prefix included', kind: 'max_chars', value: '80', field: 'title' },
    { id: 'title_no_exclamation', description: 'An exclamation mark in the title', kind: 'forbidden_regex', value: '!', field: 'title' },
    { id: 'title_no_superlative', description: 'A superlative or hype word in the title', kind: 'forbidden_regex', value: '\\b(best|fastest|easiest|simplest|ultimate|most powerful|world\'?s first|first ever|blazing(ly)? fast|ai[- ]?powered|next[- ]?gen(eration)?|revolution[a]r\\w*|ground[b]reaking|game[- ]?chang\\w*)\\b', field: 'title' },
    { id: 'title_no_listicle_number', description: 'A listicle number in the title', kind: 'forbidden_regex', value: '\\b\\d+\\s+(ways|reasons|tips|tricks|things|tools|lessons)\\b', field: 'title' },
    { id: 'title_no_dash', description: 'Em or en dash in the title', kind: 'forbidden_regex', value: '[\u2012\u2013\u2014\u2015]', field: 'title' },
    { id: 'title_no_banned_verb', description: 'The banned launch verb in the title', kind: 'forbidden_regex', value: '\\bsh[i]p(s|ped|ping)?\\b', field: 'title' },
    { id: 'title_no_link', description: 'A link in the title', kind: 'forbidden_regex', value: 'https?://|\\{APP_URL\\}', field: 'title' },
    { id: 'body_min_words', description: 'Body under 100 words', kind: 'min_words', value: '100', field: 'body' },
    { id: 'body_max_words', description: 'Body over 200 words', kind: 'max_words', value: '200', field: 'body' },
    { id: 'body_no_exclamation', description: 'An exclamation mark in the body', kind: 'forbidden_regex', value: '!', field: 'body' },
    { id: 'body_no_hashtag', description: 'A hashtag', kind: 'forbidden_regex', value: '(^|\\s)#[A-Za-z]\\w*', field: 'body' },
    { id: 'body_no_markdown', description: 'Markdown (headers, bold, lists); HN renders none of it', kind: 'forbidden_regex', value: '(^|\\n)[ \\t]*(#{1,6}\\s|[-*]\\s|\\d+\\.\\s)|\\*\\*[^*\\n]+\\*\\*|__[^_\\n]+__', field: 'body' },
    { id: 'body_no_vote_ask', description: 'A vote ask or launch-day language', kind: 'forbidden_regex', value: '\\b(upvotes?|up-votes?|vote(s|d|ing)?|front ?page|leaderboard|support us|show (some|your) (love|support)|help us (get|reach|trend|climb)|smash|launch(ing)? (day|today)|we\'?re live|now live)\\b', field: 'body' },
    { id: 'body_no_banned_verb', description: 'The banned launch verb', kind: 'forbidden_regex', value: '\\bsh[i]p(s|ped|ping)?\\b', field: 'body' },
    { id: 'body_no_hype', description: 'Hype words', kind: 'forbidden_regex', value: '\\b(game[- ]?chang\\w*|revolution\\w*|ground[b]reaking|v[i]ral|seamless\\w*|unleash\\w*|supercharg\\w*|\\d+x( faster| better| more)?|\\d+ ?times (faster|better|more)|blazing\\w*|cutting[- ]?edge|state[- ]of[- ]the[- ]art|next[- ]?gen(eration)?|ai[- ]?powered|the future of|best[- ]in[- ]class|world[- ]class|effortless\\w*|lightning[- ]fast)\\b', field: 'body' },
    { id: 'body_no_marketing_phrase', description: 'Marketing phrasing', kind: 'forbidden_regex', value: '\\b(excited|thrilled|proud to|delighted|pleased to announce|announc(e|ing)|join us|sign up now|get started today|limited time|don\'?t miss|game on|check out our|we\'?d love your support)\\b', field: 'body' },
    { id: 'body_no_ranking_comparison', description: 'Better-than-X positioning', kind: 'forbidden_regex', value: '\\b(better than|worse than|\\w+[- ]killer|blows? \\w+ (away|out of the water)|puts? \\w+ to shame|leaves? \\w+ in the dust|unlike (most|other|every|all) \\w+)\\b', field: 'body' },
    { id: 'body_no_dash', description: 'Em or en dash', kind: 'forbidden_regex', value: '[\u2012\u2013\u2014\u2015]', field: 'body' },
    { id: 'body_no_rhetorical_opener', description: 'Rhetorical-question opener', kind: 'forbidden_regex', value: '^[ \\t]*(hi hn,?[ \\t]*)?(ever|have you|do you|did you|what if|why do|why is|tired of|are you|imagine|wouldn\'?t it be)\\b[^.\\n]*\\?', field: 'body' },
    { id: 'body_app_url_max_once', description: '{APP_URL} more than once', kind: 'max_count', value: '1', field: 'body' },
    { id: 'body_max_paragraph_breaks', description: 'More than five paragraphs', kind: 'max_count', value: '4', field: 'body' },
    { id: 'body_max_raw_links', description: 'More than one raw link', kind: 'max_count', value: '1', field: 'body' },
  ],
  'newsletter_pitch': [
    { id: 'pitch_min_words', description: 'Pitch under 100 words', kind: 'min_words', value: '100', field: 'pitch' },
    { id: 'pitch_max_words', description: 'Pitch over 150 words', kind: 'max_words', value: '150', field: 'pitch' },
    { id: 'subject_max_chars', description: 'Subject over 70 characters', kind: 'max_chars', value: '70', field: 'subject' },
    { id: 'subject_no_exclamation', description: 'An exclamation mark in the subject', kind: 'forbidden_regex', value: '!', field: 'subject' },
    { id: 'pitch_no_exclamation', description: 'An exclamation mark in the pitch', kind: 'forbidden_regex', value: '!', field: 'pitch' },
    { id: 'subject_no_emoji', description: 'An emoji in the subject', kind: 'forbidden_regex', value: '[\\u{1F000}-\\u{1FAFF}\\u{2600}-\\u{27BF}]', field: 'subject' },
    { id: 'pitch_no_emoji', description: 'An emoji in the pitch', kind: 'forbidden_regex', value: '[\\u{1F000}-\\u{1FAFF}\\u{2600}-\\u{27BF}]', field: 'pitch' },
    { id: 'subject_no_launch_bait', description: 'Launch bait, a pipe separator or urgency in the subject', kind: 'forbidden_regex', value: 'live on (product hunt|ph)\\b|launching today|today only|\\burgent\\b|\\bimportant\\b|\\||only (24|48) hours|limited time|last chance|don.?t miss', field: 'subject' },
    { id: 'pitch_link_present', description: 'Missing the {APP_URL} placeholder', kind: 'forbidden_regex', value: '(?<![\\s\\S])(?![\\s\\S]*\\{APP_URL\\})', field: 'pitch' },
    { id: 'pitch_link_once', description: '{APP_URL} more than once', kind: 'forbidden_regex', value: '\\{APP_URL\\}[\\s\\S]*\\{APP_URL\\}', field: 'pitch' },
    { id: 'pitch_no_attachments', description: 'An attachment, deck or press kit mention', kind: 'forbidden_regex', value: '\\battach(ed|ment|ments)?\\b|see (the )?(deck|pdf|attached)|\\benclosed\\b|press kit|gallery highlights', field: 'pitch' },
    { id: 'pitch_no_filler', description: 'A stock opener or closer', kind: 'forbidden_regex', value: 'hope this (email |message |note )?finds you|finds you well|hope you.?re (well|doing well)|hope all is well|to whom it may concern|dear (sir|madam|editor|editorial|team)|thanks for your time|thank you for your time|reaching out|touch base|additional info|^\\s*p\\.?s\\.?[:\\s]', field: 'pitch' },
    { id: 'pitch_no_press_release', description: 'Press-release phrasing', kind: 'forbidden_regex', value: 'proud to announce|thrilled|excited to (announce|share|introduce)|today announced|pleased to (announce|share)|the leading|industry.leading|world.class|best.in.class|for immediate release|press release|\\bdisrupt', field: 'pitch' },
    { id: 'pitch_no_asks', description: 'A vote, feature, share or favour ask', kind: 'forbidden_regex', value: 'upvote|vote for|\\bvoting\\b|feature us|featuring us|would mean (the world|a lot|so much)|means the world|share (this|it) with your|help us reach|spread the word|shout.?out|give us a (mention|plug)|in exchange for', field: 'pitch' },
    { id: 'pitch_no_fomo', description: 'Urgency or scarcity language', kind: 'forbidden_regex', value: 'only (24|48) hours|limited time|last chance|don.?t miss|before it.?s gone|act now|\\bhurry\\b|ends (today|tonight|soon)|\\bdeadline\\b', field: 'pitch' },
    { id: 'pitch_no_competitor_framing', description: 'Comparative or rival-naming framing', kind: 'forbidden_regex', value: 'better than|\\bunlike\\b|\\bvs\\b|\\bversus\\b|alternative to|replacement for|[a-z]+.killer\\b', field: 'pitch' },
    { id: 'pitch_no_bullets_or_headers', description: 'A markdown header or list', kind: 'forbidden_regex', value: '^(#{1,6} |[-*•] |\\d+[.)] )', field: 'pitch' },
    { id: 'pitch_no_caps_labels', description: 'An ALL CAPS section label at a line start', kind: 'forbidden_regex', value: '^[A-Z][A-Z \'&/]{2,}:', field: 'pitch', flags: '' },
    { id: 'pitch_no_hashtags', description: 'A hashtag', kind: 'forbidden_regex', value: '(^|\\s)#\\w+', field: 'pitch' },
    { id: 'pitch_max_paragraphs', description: 'Six or more paragraph breaks', kind: 'forbidden_regex', value: '(\\n\\s*\\n[\\s\\S]*){6}', field: 'pitch' },
    { id: 'pitch_no_hype_or_nx', description: 'Hype words or an Nx-faster claim', kind: 'forbidden_regex', value: '\\b\\d+x (faster|better|more|cheaper|quicker)\\b|\\b1[0]x\\b|vir[a]l|unle[a]sh|superch[a]rge|ground[b]reaking|revolution[a]r|game.?ch[a]ng', field: 'pitch' },
    { id: 'pitch_no_banned_verb', description: 'The banned launch verb', kind: 'forbidden_regex', value: '\\bsh[i]p(s|ped|ping)?\\b', field: 'pitch' },
  ],
};
